try:
    a = 5 / 0
except Exception as error:
    print(error)
